#!/usr/bin/ruby
## Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with
#  and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of
#  the even-valued terms.
prefib = 1
fib = 2
total = 0
while fib < 4000000 do
	total += fib if fib % 2 == 0
	tempfib = fib
	fib += prefib
	prefib = tempfib
end

puts total
