#!/usr/bin/python
"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
"""

if __name__ == "__main__":
        sum = 0
        i = 1
	backone = 2
	temp = 0
        while (i <= 4000000):
                if i%2 == 0:
                        sum = sum + i
		if i == 1 or i == 2:
			i = i + 1
		else:
			temp = i
			i = i + backone
			backone = temp			

        print sum
